### PR TITLE
fix expire time for jwt

### LINKED ISSUE #1: apple default time is 14 hours 30minutes too long
Need to set jwt expire time to `182d` (days) or `15724800`

### PR DESCRIPTION
**Pull request by generalandrew**
closes #1

### CODE REVIEW

**Comment by scottrhoyt** [comment]
Thanks for reporting this and fixing it!

**Comment by scottrhoyt** [comment]
@generalandrew, I knew I got that value from somewhere, so I just went back to reread the Apple Music API docs. They explicitly list the expiration time as 15777000 seconds [here](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/AppleMusicWebServicesReference/SetUpWebServices.html#//apple_ref/doc/uid/TP40017625-CH2-SW1). Did you have an experience that indicated that value doesn't work? (It wouldn't be the first time I've found something in Apple Music API that doesn't work as documented 😬)

**Comment by generalandrew** [comment]
@scottrhoyt This is exactly what I was experiencing. Using that time returns an unauthorized error every time you try to request data even though the token is a valid jwt. Changing the expiration date to shave off those 14 hours fixes the issue. #RIPSteve

**Comment by scottrhoyt** [comment]
🤦‍♂️. Thanks for figuring that out!

**Pull request merged**
